manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: hotp4ck
      url-base: https://github.com/yg3988
  projects:
    - name: zmk
      remote: hotp4ck
      revision: sensor-driver-max17048
      import: app/west.yml
  self:
    path: config
